version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"


sphinx:
  fail_on_warning: true    
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .  

python:
   install:
   - requirements: docs/requirements.txt

formats:
  - pdf
  - epub      