[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tutorial-dqrobotics-with-coppeliasim"
authors = [{name = "Juan Jose Quiroz Omana", email = "juanjqogm@gmail.com"}]
dynamic = ["version", "description"]
