[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MyProject"
authors = [{name = "Gabriel Garcia Marquez", email = "myemail.com"}]
dynamic = ["version", "description"]